CC = gcc
CPPFLAGS = 
CFLAGS = -std=c11 -D_XOPEN_SOURCE=700 -O2 -Wall -Wextra -Wformat=2

.DEFAULT: all
.PHONY: all
all: hello2 arrays

clean: 
	rm -f *.o

distclean: clean
	rm -f tftpd

hellomake: hello2

arraymake: arrays

hmake: histogram

mcompare: compare
